default: true

# README/spec docs often exceed 80 chars (URLs, diagrams, long sentences)
MD013: false

# Allow multiple blank lines (not a quality issue here)
MD012: false

# Allow bold labels (e.g., **Author**) if they exist
MD036: false

# Don’t require blank lines around headings/lists (too picky for portfolio docs)
MD022: false
MD032: false

# Allow inline HTML if used in badges/formatting
MD033: false

# Allow duplicate headings
MD024: false
